name: Deploy to Vercel

on:
  push:
    branches:
      - master  # Cambia esto si usas otra rama como "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Usa la versión de Node.js que necesites

      - name: Install dependencies
        run: npm install

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Token de Vercel
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  # ID de la organización en Vercel
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # ID del proyecto en Vercel
